// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfIrpOvS4eYyuWNs08bntUl2gT07s11qE',
    appId: '1:529853329719:web:44c04a1c5a5619086f6ab2',
    messagingSenderId: '529853329719',
    projectId: 'money-maker-2a99a',
    authDomain: 'money-maker-2a99a.firebaseapp.com',
    storageBucket: 'money-maker-2a99a.appspot.com',
    measurementId: 'G-RL1EMS89SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVc7pHVoNKK9wchnDSr7ABWAjphLGSgWc',
    appId: '1:529853329719:android:0737273a66cb99516f6ab2',
    messagingSenderId: '529853329719',
    projectId: 'money-maker-2a99a',
    storageBucket: 'money-maker-2a99a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAwZngRR2o5tFrM8gIsuaYESSbty7YIVo',
    appId: '1:529853329719:ios:26b5f65d297b6e346f6ab2',
    messagingSenderId: '529853329719',
    projectId: 'money-maker-2a99a',
    storageBucket: 'money-maker-2a99a.appspot.com',
    iosBundleId: 'com.example.moneyMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAwZngRR2o5tFrM8gIsuaYESSbty7YIVo',
    appId: '1:529853329719:ios:26b5f65d297b6e346f6ab2',
    messagingSenderId: '529853329719',
    projectId: 'money-maker-2a99a',
    storageBucket: 'money-maker-2a99a.appspot.com',
    iosBundleId: 'com.example.moneyMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfIrpOvS4eYyuWNs08bntUl2gT07s11qE',
    appId: '1:529853329719:web:7410e4332070a1bc6f6ab2',
    messagingSenderId: '529853329719',
    projectId: 'money-maker-2a99a',
    authDomain: 'money-maker-2a99a.firebaseapp.com',
    storageBucket: 'money-maker-2a99a.appspot.com',
    measurementId: 'G-0QM8WJ6ZE0',
  );
}
